package exception;

import java.time.LocalDate;
import java.util.Scanner;

public class Ex04 {
	private static Scanner ip = new Scanner(System.in);
//NÃªÌ?u code xaÌ‰y ra ngoaÌ£i lÃªÌ£ => JVM neÌ?m ra thÃ´ng tin ngoaÌ£i lÃªÌ£ trong console va kÃªÌ?t thuÌ?c chÆ°Æ¡ng triÌ€nh
	
	public static void main(String[] args) {
       System.out.println("Enter a: ");
       int a=Integer.parseInt(ip.nextLine());
       
       System.out.println("Enter b: ");
       int b=Integer.parseInt(ip.nextLine());
       try {
       int x=div(a,b);
       System.out.println("Result: "+x);
       }catch(ArithmeticException e) {
    	   System.out.println("---Jump to catch---");
       }
      System.out.println("Thread main end !");
	}
	
	private static int div(int a,int b) {
		if(a==0) {
			System.out.println("Throw Exception");
			throw new ArithmeticException();
		}
		System.out.println("-b/a");
		return -b/a;
	}
}
